### ISSUE TITLE
Name bikeshedding

### ISSUE THREAD

**Issue by Dignifiedquire** [ipfs/station#46]
`electron-app` is boring, lets find something cool and awesome :)

**Comment by jbenet** [comment]
some suggestions:
- Station
- IPFS App
- IPFS Node
- IPFS
- IPApp
- INode

**Comment by bcomnes** [comment]
I would stick with capital IPFS.  It's simple, and differentiates itself from the cli with capital letters.  If ambiguity between the two becomes an an issue, maybe a codename like Station would be good. 

I would keep the word node away from anything not specifically related to ipfs code written for node since its super confusing whenever I see that word in this project.

**Comment by RichardLitt** [comment]
The capital // lowercase ambiguity will swiftly become an issue. Station is a good suggestion.

**Comment by Dignifiedquire** [comment]
I like station as well.

**Comment by Dignifiedquire** [comment]
`station` is sadly taken on npm already, we could go with `ipfs-station` or use a scoped package. I also contacted the author of the package: https://github.com/Marak/station/issues/3 if he would be willing to give the name up.

**Comment by jbenet** [comment]
I'd prefer using ipfs-station as a pkg name to scope all our modules. But we can still just use "Station" if we want to in the UI/ux (both "station" and "IPFS Station" sound great)



—

**Comment by Dignifiedquire** [comment]
Done in https://github.com/ipfs/station/commit/5a123c2c9ed0fe3ec86aad336417ddbefdea9243
